[package]
name = "adk-rs-examples"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false
description = "Examples for adk-rs."

[lints]
workspace = true

[dependencies]
adk-rs-error.workspace = true
adk-rs-genai-types.workspace = true
adk-rs-core.workspace = true
adk-rs-agents.workspace = true
adk-rs-runner.workspace = true
adk-rs-tools.workspace = true
adk-rs-services-mem.workspace = true
adk-rs-providers-gemini.workspace = true
adk-rs-providers-anthropic.workspace = true
adk-rs-providers-openai.workspace = true
adk-rs-cli.workspace = true
adk-rs-eval.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
serde_json.workspace = true
serde = { workspace = true, features = ["derive"] }
schemars.workspace = true
futures.workspace = true
async-trait.workspace = true
tracing.workspace = true
